### ISSUE TITLE
[typedstore] Protect DB dump/count_keys against safety violations

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/mysten-infra#128]
#103 introduced macros which equip some tables with the ability to dump tables (#116 added some functionality to this).

One important TODO remains on this particular topic: the dump/count_keys capability is made for DBs opened as secondary.
https://github.com/MystenLabs/mysten-infra/blob/e46c6745e8a9c5c5c0dbddf7d84064d0df68b1e1/crates/typed-store-macros/src/lib.rs#L252
https://github.com/MystenLabs/mysten-infra/blob/main/crates/typed-store-macros/src/lib.rs#L274

It's not necessarily clear to me that we need the feature of opening a DB as R/W through macros, and if it is it's not clear that we need one implementation with both :
- open as primary,
- open as secondary.
Rather, it might make more sense to have two structs, one that has read_only + dump capability, and one that has R/W opening and no dump.

**Comment by oxade** [comment]
@huitseeker 
> It's not necessarily clear to me that we need the feature of opening a DB as R/W through macros

Right, this was never the original plan. The motivation for using macros was request from Todd to reduce how much code clients had to change when adding/removing struct entries. The initial macro-less logic required lots of refactoring anytime tables changed. Macros seemed like the only way to get compile time assurances.

> Rather, it might make more sense to have two structs, one that has read_only + dump capability, and one that has R/W opening and no dump.

So on the topic of having two structs, it seems like yet another struct to be maintained, except if I do the following:
- the same way I have a configurator struct which is auto derived, I can have a `ReadOnlyStruct` which is also auto derived. Meanwhile the original struct only does single owner RW.

So for a struct 
```
#[derive(DBMapUtils)]
struct Tables {
    table1: DBMap<String, String>,
    table2: DBMap<i32, String>,
    table3: DBMap<i32, String>,
    table4: DBMap<i32, String>,
}
```
which allows RW only, a complimentary struct `TablesReadOnly` is auto-derived, which exposes `dump`/`count_keys` and only allows read-only open. This fixes the invariant violation.

```
struct TablesReadOnly {
    table1: DBMap<String, String>,
    table2: DBMap<i32, String>,
    table3: DBMap<i32, String>,
    table4: DBMap<i32, String>,
}
```

**Comment by oxade** [comment]
Fixed by separating out the structs. Only secondary structs can open dump
