### ISSUE TITLE
[typed_store] Write an iterator-based variant of `multi_get`

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/mysten-infra#14]
- `multi_get` was added in #2 
- its argument is a slice of values, leading to value copies, because we serialize each of these before passing them to the DB:
  `multi_get(&self, keys: &[K]) -> Result<Vec<Option<V>>>`
 - We should instead take an iterator with references or values for keys at `Item` (`std::borrow::Borrow` is useful here),
 - inspiration can be gleaned by the type of the `delete_batch` function, which takes the same sort of argument:
  https://github.com/MystenLabs/mysten-infra/blob/5221b8ff87e18a1bff2ffe930711685d54c04062/typed-store/src/rocks/mod.rs#L164-L168
- this change should then be propagated downstream to packages using this.

**Comment by huitseeker** [comment]
This was done! https://github.com/MystenLabs/mysten-infra/pull/38/files#diff-b360df397831a1d4239f8dfc8335392f602f32e2d192f0507f60bb55f73b63f1

**Comment by akichidis** [comment]
> This was done! https://github.com/MystenLabs/mysten-infra/pull/38/files#diff-b360df397831a1d4239f8dfc8335392f602f32e2d192f0507f60bb55f73b63f1

oh nice, two birds one stone! :)
