### ISSUE TITLE
Re-activate Tokio Console

### ISSUE THREAD

**Issue by huitseeker** [MystenLabs/mysten-infra#154]
Actually I'm not sure this is going to work.
I can connect with Tokio-console to a Sui-node binary compiled by these changes, and with TOKIO_CONSOLE=true env var.  However, no tasks are displayed.

I followed all the recommendations in https://docs.rs/console-subscriber/0.1.7/console_subscriber/#enabling-tokio-instrumentation

You have to enable TRACE logs for Tokio and tracing, which just spews an unacceptable amount of logs.  And even after that I still am not getting any instrumentation.  Granted I had no transactions, but I should be able to see something happening just with consensus and checkpoints, etc.

_Originally posted by @velvia in https://github.com/MystenLabs/sui/issues/4438#issuecomment-1234863624_

**Comment by huitseeker** [comment]
Here's one place where this would be useful to test:  any of the integration tests in https://github.com/MystenLabs/sui/issues/5217
These are in a live lock, and it would be tremendously useful to run their binaries on tokio-console.

**Comment by velvia** [comment]
I had a chat with the Tokio-Console folks.  The essential problem is that we are doing a global filter for the log level, which is messing up the per-layer filtering Tokio Console does.   More info:

https://discord.com/channels/500028886025895936/1021281253997170709

> what you're doing is configuring your reloadable EnvFilter as a global filter. that means that it applies to all the layers, including the ConsoleLayer from console_subscriber

i'm guessing you only want it to apply to some other layers, which you can do using per-layer filtering: https://docs.rs/tracing-subscriber/latest/tracing_subscriber/layer/index.html#per-layer-filtering
[tracing_subscriber::layer - Rust](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/layer/index.html)
The [`Layer`] trait, a composable abstraction for building `Subscriber`s.
it looks like you're using a Vec of layers for your other layers, so what you probably want to do is apply your filter only to the Vec, and add the console-subscriber layer separately


[Evan] So I will make this change and think  a bit about the different filtering needs of each layer.  Namely, jaeger should have a different filtering mechanism than the others (sampled, all the way down to TRACE).  Maybe this should be true for automatic span latency generation too.  I'm also not sure how helpful enabling spans are for logs.
